LOGIN_HTML = r'''<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>ALISON · NEXUS</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700;800;900&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
<style>
:root{--bg:#05070a;--panel:#0b1015;--line:#1c2830;--text:#eef7f4;--muted:#7f929b;--a:#42f5c5;--a2:#26b8ff;--danger:#ff637d}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:Vazirmatn,sans-serif}body{display:grid;place-items:center;overflow:hidden}
body:before{content:"";position:fixed;inset:0;background:linear-gradient(rgba(66,245,197,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(66,245,197,.035) 1px,transparent 1px);background-size:46px 46px;mask-image:linear-gradient(to bottom,black,transparent 80%)}
.wrap{position:relative;width:min(1050px,94vw);min-height:620px;display:grid;grid-template-columns:1.15fr .85fr;border:1px solid var(--line);background:#080c10;box-shadow:0 40px 120px #000;border-radius:34px;overflow:hidden}
.visual{position:relative;padding:48px;display:flex;flex-direction:column;justify-content:space-between;background:radial-gradient(circle at 70% 25%,rgba(66,245,197,.12),transparent 35%),linear-gradient(135deg,#0a1215,#06090c)}
.visual h1{font:700 clamp(54px,8vw,96px)/.9 'Space Grotesk',sans-serif;letter-spacing:-.08em;margin:0;color:#f2fffb}.visual h1 span{color:var(--a)}.visual p{max-width:470px;color:#8ca0a9;line-height:2;font-size:14px}.rings{position:absolute;inset:auto 8% 18% auto;width:280px;height:280px;border:1px solid #2a4648;border-radius:50%;box-shadow:0 0 80px rgba(66,245,197,.08)}.rings:before,.rings:after{content:"";position:absolute;inset:35px;border:1px dashed #294144;border-radius:50%}.rings:after{inset:78px;border:1px solid #245d5b}.signal{position:absolute;right:140px;bottom:150px;width:8px;height:8px;background:var(--a);border-radius:50%;box-shadow:0 0 24px var(--a)}
.login{padding:48px;background:#090d11;display:flex;flex-direction:column;justify-content:center}.eyebrow{font-size:11px;letter-spacing:.18em;color:var(--a);font-weight:800}.login h2{font-size:30px;margin:10px 0 6px}.login .sub{color:var(--muted);font-size:12px;margin-bottom:30px}.field{margin:12px 0}.field label{display:block;font-size:11px;color:#9badb4;margin-bottom:8px}.field input{width:100%;padding:15px 16px;border-radius:15px;border:1px solid #1e2b33;background:#06090c;color:#fff;outline:0;font:inherit;transition:.2s}.field input:focus{border-color:#38dcb9;box-shadow:0 0 0 4px rgba(66,245,197,.07)}button{border:0;font:inherit;cursor:pointer}.go{width:100%;margin-top:14px;padding:15px;border-radius:15px;background:var(--a);color:#03110c;font-weight:900;box-shadow:0 12px 35px rgba(66,245,197,.16)}.meta{display:flex;justify-content:space-between;margin-top:18px;color:#566970;font-size:10px}.dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:var(--a);box-shadow:0 0 12px var(--a);margin-left:6px}
@media(max-width:760px){body{overflow:auto;padding:12px}.wrap{grid-template-columns:1fr;min-height:auto}.visual{min-height:260px;padding:28px}.visual h1{font-size:56px}.rings{width:190px;height:190px;right:-25px;bottom:25px}.signal{right:65px;bottom:120px}.login{padding:30px 24px}.visual p{font-size:12px}}
</style></head>
<body><main class="wrap"><section class="visual"><div><div class="eyebrow">ALISON / NEXUS CONTROL</div><h1>ALISON<br><span>NEXUS</span></h1><p>مرکز کنترل نسل جدید برای مدیریت نودها، کلاینت‌ها، اشتراک‌ها و وضعیت زنده شبکه.</p></div><div><span class="dot"></span><small style="color:#7f929b">SYSTEM READY · SECURE CONTROL</small></div><div class="rings"></div><i class="signal"></i></section><section class="login"><div class="eyebrow">SECURE ENTRY</div><h2>ورود به مرکز کنترل</h2><div class="sub">دسترسی مدیریتی خود را وارد کنید.</div><form method="post" action="/login"><div class="field"><label>نام کاربری</label><input name="username" autocomplete="username" required></div><div class="field"><label>رمز عبور</label><input name="password" type="password" autocomplete="current-password" required></div><button class="go" type="submit">ورود به NEXUS</button></form><div class="meta"><span>ALISON CONTROL SUITE</span><span>LOCAL AUTH</span></div></section></main></body></html>'''

DASHBOARD_HTML = r'''<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>ALISON · NEXUS</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700;800;900&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.34.0/dist/tabler-icons.min.css">
<style>
:root{--bg:#05080b;--panel:#0a0f13;--panel2:#0d1419;--line:#1b2930;--line2:#24353d;--text:#edf8f5;--muted:#81939b;--soft:#52636b;--a:#42f5c5;--b:#25baff;--y:#f6c453;--r:#ff647e;--shadow:0 28px 90px rgba(0,0,0,.38)}
*{box-sizing:border-box}html,body{margin:0;background:var(--bg);color:var(--text);font-family:Vazirmatn,sans-serif}body{min-height:100vh}button,input,select{font:inherit}button{cursor:pointer}.shell{display:grid;grid-template-columns:250px 1fr;min-height:100vh}.rail{position:sticky;top:0;height:100vh;border-left:1px solid var(--line);background:#070b0e;padding:20px 14px;display:flex;flex-direction:column;z-index:20}.brand{display:flex;align-items:center;gap:10px;padding:6px 8px 25px}.brandmark{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:#0e1719;border:1px solid #28413f;color:var(--a);font:800 16px 'Space Grotesk'}.brand strong{font:700 17px 'Space Grotesk';letter-spacing:-.04em}.brand small{display:block;color:var(--soft);font-size:8px;letter-spacing:.16em;margin-top:2px}.group{margin:12px 0 7px;padding:0 10px;color:#49606a;font-size:8px;font-weight:900;letter-spacing:.15em}.nav{display:grid;gap:4px}.nav button{position:relative;border:0;background:transparent;color:#8799a1;border-radius:12px;padding:11px 12px;display:flex;align-items:center;gap:11px;text-align:right;font-size:11px;transition:.18s}.nav button i{font-size:18px;width:20px;text-align:center}.nav button:hover{background:#0d1519;color:#dcebe8}.nav button.active{background:#0d1918;color:var(--a);border:1px solid #183e3a}.nav button.active:before{content:"";position:absolute;right:-1px;width:3px;height:20px;background:var(--a);border-radius:3px}.rail-bottom{margin-top:auto;border-top:1px solid var(--line);padding-top:14px}.online{display:flex;align-items:center;gap:7px;color:var(--a);font-size:9px;padding:10px}.online b{width:6px;height:6px;border-radius:50%;background:var(--a);box-shadow:0 0 12px var(--a)}
.main{min-width:0}.top{height:70px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 26px;position:sticky;top:0;background:rgba(5,8,11,.9);backdrop-filter:blur(16px);z-index:15}.crumb{font-size:11px;color:var(--muted)}.crumb b{color:var(--text);margin-left:7px}.actions{display:flex;gap:8px}.iconbtn{width:36px;height:36px;border:1px solid var(--line);background:#0a1014;color:#91a6ad;border-radius:11px}.iconbtn:hover{border-color:#31504f;color:var(--a)}.mobile-menu{display:none}
.content{padding:26px;max-width:1500px;margin:auto}.view{display:none}.view.active{display:block;animation:rise .2s ease}@keyframes rise{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}.hero{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.eyebrow{font-size:9px;letter-spacing:.18em;color:var(--a);font-weight:900}.hero h1{font-size:30px;margin:6px 0 5px;letter-spacing:-.04em}.hero p{margin:0;color:var(--muted);font-size:11px}.primary{border:1px solid #2a7161;background:var(--a);color:#03120d;padding:11px 15px;border-radius:12px;font-size:10px;font-weight:900}.ghost{border:1px solid var(--line2);background:#0b1115;color:#a8bbc1;padding:10px 13px;border-radius:12px;font-size:10px;font-weight:800}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metric{background:linear-gradient(145deg,#0b1115,#080c10);border:1px solid var(--line);border-radius:17px;padding:17px;min-height:120px}.metric .k{display:flex;justify-content:space-between;color:#6e8189;font-size:9px}.metric .ico{color:var(--a);font-size:18px}.metric strong{display:block;font:700 28px 'Space Grotesk';margin-top:16px}.metric small{color:#647780;font-size:9px}.layout2{display:grid;grid-template-columns:1.55fr 1fr;gap:12px;margin-top:12px}.panel{background:#090e12;border:1px solid var(--line);border-radius:19px;overflow:hidden}.panelhead{padding:16px 18px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.panelhead b{font-size:11px}.panelhead span{color:var(--soft);font-size:8px;letter-spacing:.1em}.chart{height:260px;padding:18px;display:flex;align-items:end;gap:7px}.bar{flex:1;background:linear-gradient(to top,#183d39,#42f5c5);border-radius:5px 5px 2px 2px;min-height:8px;opacity:.82}.feed{padding:8px 15px 15px}.feedrow{display:grid;grid-template-columns:8px 1fr auto;gap:10px;align-items:center;padding:11px 3px;border-bottom:1px solid #111b20}.feedrow:last-child{border:0}.feedrow i{width:7px;height:7px;border-radius:50%;background:var(--a);box-shadow:0 0 9px var(--a)}.feedrow b{display:block;font-size:10px}.feedrow small{display:block;color:var(--soft);font-size:8px;margin-top:2px}.feedrow time{color:#5c7078;font-size:8px}
.sectionbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.sectionbar h2{margin:0;font-size:19px}.sectionbar p{margin:4px 0 0;color:var(--muted);font-size:9px}.tools{display:flex;gap:7px}.search{background:#090f13;border:1px solid var(--line);border-radius:12px;padding:10px 12px;color:#dcebe8;outline:0;min-width:210px;font-size:10px}.search:focus{border-color:#2b6259}.node-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.node{position:relative;background:#090f13;border:1px solid var(--line);border-radius:18px;padding:17px;overflow:hidden}.node:after{content:"";position:absolute;inset:auto -40px -80px auto;width:150px;height:150px;background:radial-gradient(circle,rgba(66,245,197,.08),transparent 70%)}.node-top{display:flex;justify-content:space-between}.node-icon{width:42px;height:42px;border-radius:13px;background:#0c1818;border:1px solid #1b3936;display:grid;place-items:center;color:var(--a);font-size:21px}.status{font-size:8px;color:var(--a);padding:5px 8px;border-radius:999px;background:#0a1c18;border:1px solid #183e36}.node h3{font-size:13px;margin:15px 0 3px}.node .proto{font-size:8px;color:var(--soft)}.node-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:15px}.node-stats div{background:#070c10;border:1px solid #101a20;border-radius:9px;padding:8px}.node-stats small{display:block;color:#566971;font-size:7px}.node-stats b{display:block;font-size:10px;margin-top:3px}.node-actions{display:flex;gap:6px;margin-top:12px}.node-actions button{flex:1;padding:8px;border-radius:9px;border:1px solid var(--line);background:#0c1418;color:#91a6ad;font-size:8px}.node-actions button:hover{color:var(--a);border-color:#285149}
.forge{display:grid;grid-template-columns:1fr 340px;gap:12px}.formpanel{background:#090f13;border:1px solid var(--line);border-radius:20px;padding:20px}.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.field label{display:block;color:#657982;font-size:8px;margin-bottom:7px}.field input,.field select,.field textarea{width:100%;background:#060a0d;border:1px solid #1b2930;color:#eaf5f2;padding:11px 12px;border-radius:11px;outline:0;font-size:10px}.field input:focus,.field select:focus{border-color:#2d6c60}.field.full{grid-column:1/-1}.forge-preview{position:sticky;top:95px;background:#07100e;border:1px solid #183a34;border-radius:20px;padding:20px;min-height:320px}.passport{border:1px solid #234d46;border-radius:17px;padding:18px;background:linear-gradient(145deg,#0b1916,#07100e)}.passport .mark{color:var(--a);font:700 10px 'Space Grotesk';letter-spacing:.16em}.passport h3{font-size:22px;margin:25px 0 5px}.passport p{font-size:8px;color:#68817c}.passport .line{height:1px;background:#17312d;margin:18px 0}.miniqr{height:85px;width:85px;border:6px solid #eef8f4;background:repeating-linear-gradient(45deg,#06100d 0 3px,#fff 3px 6px);margin-top:10px}
.table{border:1px solid var(--line);border-radius:18px;overflow:hidden;background:#090f13}.thead,.tr{display:grid;grid-template-columns:1.3fr .8fr 1fr .9fr .7fr;align-items:center}.thead{padding:12px 15px;color:#566a73;font-size:8px;background:#080d10}.tr{padding:14px 15px;border-top:1px solid #111b20;font-size:9px}.tr b{font-size:10px}.badge{display:inline-flex;padding:5px 7px;border-radius:7px;background:#0c1917;border:1px solid #173e37;color:var(--a);font-size:8px}.rowactions{display:flex;gap:4px}.rowactions button{width:29px;height:29px;border:1px solid var(--line);border-radius:8px;background:#0b1216;color:#82959c}.rowactions button:hover{color:var(--a)}.empty{padding:40px;text-align:center;color:#586b73;font-size:10px}
.event-stream{border-right:1px solid #1a302d;margin-right:8px;padding-right:22px}.event{position:relative;padding:0 0 22px}.event:before{content:"";position:absolute;right:-27px;top:3px;width:9px;height:9px;background:var(--a);border-radius:50%;box-shadow:0 0 14px rgba(66,245,197,.5)}.event b{font-size:10px}.event small{display:block;color:var(--soft);font-size:8px;margin-top:4px}.subhero{background:linear-gradient(120deg,#081513,#0b1114);border:1px solid #173b35;border-radius:22px;padding:22px;display:flex;justify-content:space-between;align-items:center}.subhero h2{margin:4px 0;font-size:24px}.subhero p{margin:0;color:#6d8580;font-size:9px}.plan-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin-top:12px}.plan{background:#090f13;border:1px solid var(--line);border-radius:18px;padding:18px}.plan.featured{border-color:#2c6359}.plan h3{margin:0;font-size:14px}.price{font:700 26px 'Space Grotesk';margin:16px 0}.plan li{list-style:none;color:#6d8189;font-size:9px;padding:5px 0}.plan ul{padding:0;margin:0}.toggle{display:flex;background:#070c0f;border:1px solid var(--line);padding:3px;border-radius:11px}.toggle button{border:0;background:transparent;color:#6f838b;padding:7px 11px;border-radius:8px;font-size:8px}.toggle button.on{background:#15332e;color:var(--a)}
.modal{position:fixed;inset:0;background:rgba(0,0,0,.68);backdrop-filter:blur(7px);display:none;align-items:center;justify-content:center;z-index:60;padding:15px}.modal.show{display:flex}.modalbox{width:min(620px,100%);max-height:90vh;overflow:auto;background:#090f13;border:1px solid #23343b;border-radius:22px;box-shadow:var(--shadow);padding:20px}.modalhead{display:flex;justify-content:space-between;align-items:center}.modalhead h3{margin:0;font-size:15px}.close{border:1px solid var(--line);background:#0b1216;color:#9badb4;border-radius:9px;width:32px;height:32px}.toast{position:fixed;bottom:22px;left:50%;transform:translate(-50%,120px);background:#0c1816;border:1px solid #285b50;color:#c7fff0;padding:10px 15px;border-radius:11px;font-size:9px;z-index:90;transition:.25s;box-shadow:0 12px 35px #000}.toast.show{transform:translate(-50%,0)}
@media(max-width:1050px){.node-grid{grid-template-columns:repeat(2,1fr)}.grid4{grid-template-columns:repeat(2,1fr)}.forge{grid-template-columns:1fr}.forge-preview{position:static}.plan-grid{grid-template-columns:1fr 1fr}}
@media(max-width:760px){.shell{display:block}.rail{position:fixed;inset:0 auto 0 0;width:280px;transform:translateX(-105%);transition:.25s;box-shadow:30px 0 70px #000}.rail.open{transform:none}.mobile-menu{display:block}.top{padding:0 14px}.content{padding:18px 12px}.hero{align-items:start;flex-direction:column}.layout2{grid-template-columns:1fr}.node-grid{grid-template-columns:1fr}.grid4{grid-template-columns:1fr 1fr}.table{overflow:auto}.thead,.tr{min-width:680px}.plan-grid{grid-template-columns:1fr}.formgrid{grid-template-columns:1fr}.field.full{grid-column:auto}.search{min-width:0;width:150px}}
@media(max-width:430px){.grid4{grid-template-columns:1fr}.tools{width:100%}.sectionbar{align-items:flex-end}.hero h1{font-size:25px}}
</style></head>
<body>
<div class="shell"><aside class="rail" id="rail"><div class="brand"><div class="brandmark">A</div><div><strong>ALISON</strong><small>NEXUS CONTROL</small></div></div><div class="group">COMMAND</div><nav class="nav"><button class="active" data-view="overview"><i class="ti ti-activity"></i>مرکز فرمان</button><button data-view="nodes"><i class="ti ti-radar"></i>آزمایشگاه نود</button><button data-view="clients"><i class="ti ti-user-scan"></i>Client Forge</button></nav><div class="group">ACCESS</div><nav class="nav"><button data-view="subs"><i class="ti ti-passport"></i>Access Passport</button><button data-view="plans"><i class="ti ti-box"></i>Plan Studio</button></nav><div class="group">OBSERVABILITY</div><nav class="nav"><button data-view="analytics"><i class="ti ti-chart-dots-3"></i>Signal Monitor</button><button data-view="events"><i class="ti ti-timeline-event"></i>Event Stream</button><button data-view="security"><i class="ti ti-shield-lock"></i>Security Core</button></nav><div class="group">SYSTEM</div><nav class="nav"><button data-view="settings"><i class="ti ti-adjustments-horizontal"></i>System Core</button></nav><div class="rail-bottom"><div class="online"><b></b> SYSTEM ONLINE</div><button class="nav" style="width:100%" onclick="logout()"><span style="display:flex;gap:10px;align-items:center;padding:10px 12px;color:#81939b;font-size:10px"><i class="ti ti-logout"></i> خروج</span></button></div></aside>
<main class="main"><header class="top"><div style="display:flex;align-items:center;gap:10px"><button class="iconbtn mobile-menu" onclick="toggleRail()"><i class="ti ti-menu-2"></i></button><div class="crumb"><b>ALISON</b> / <span id="crumb">مرکز فرمان</span></div></div><div class="actions"><button class="iconbtn" onclick="refreshAll()" title="Refresh"><i class="ti ti-refresh"></i></button><button class="iconbtn" onclick="openDiagnostics()" title="Diagnostics"><i class="ti ti-terminal-2"></i></button></div></header>
<div class="content">
<section class="view active" id="view-overview"><div class="hero"><div><div class="eyebrow">NEXUS / COMMAND CENTER</div><h1>مرکز فرمان شبکه</h1><p>نمای زنده از نودها، کلاینت‌ها، اشتراک‌ها و رویدادهای سیستم.</p></div><button class="primary" onclick="show('clients');sound('success')"><i class="ti ti-user-plus"></i> ساخت کلاینت</button></div><div class="grid4"><div class="metric"><div class="k">نودهای فعال <i class="ti ti-radar ico"></i></div><strong id="mNodes">—</strong><small>ACTIVE NODES</small></div><div class="metric"><div class="k">کلاینت‌ها <i class="ti ti-users ico"></i></div><strong id="mClients">—</strong><small>REGISTERED CLIENTS</small></div><div class="metric"><div class="k">ترافیک <i class="ti ti-chart-area-line ico"></i></div><strong id="mTraffic">—</strong><small>USED TRAFFIC</small></div><div class="metric"><div class="k">اتصال زنده <i class="ti ti-bolt ico"></i></div><strong id="mConn">—</strong><small>LIVE SESSIONS</small></div></div><div class="layout2"><div class="panel"><div class="panelhead"><b>NETWORK PULSE</b><span>LIVE 24H</span></div><div class="chart" id="chart"></div></div><div class="panel"><div class="panelhead"><b>EVENT STREAM</b><span>RECENT</span></div><div class="feed" id="feed"></div></div></div></section>
<section class="view" id="view-nodes"><div class="sectionbar"><div><h2>Network Lab</h2><p>مدیریت Inboundها با ساختار ماژولار و وضعیت لحظه‌ای.</p></div><div class="tools"><input class="search" id="nodeSearch" placeholder="جستجوی نود..." oninput="renderNodes()"><button class="primary" onclick="openCreateInbound()">+ Inbound جدید</button></div></div><div class="node-grid" id="nodesGrid"></div></section>
<section class="view" id="view-clients"><div class="sectionbar"><div><h2>Client Forge</h2><p>ساخت و مدیریت Identityهای اتصال.</p></div><div class="tools"><input class="search" id="clientSearch" placeholder="جستجوی کلاینت..." oninput="renderClients()"></div></div><div class="forge"><div class="formpanel"><div class="eyebrow">IDENTITY BUILDER</div><h2 style="margin:7px 0 18px">ساخت کلاینت پیشرفته</h2><div class="formgrid"><div class="field"><label>نام کلاینت</label><input id="cLabel" placeholder="YAHYA-PRO"></div><div class="field"><label>Inbound</label><select id="cInbound"></select></div><div class="field"><label>حجم (GB)</label><input id="cLimit" type="number" value="50"></div><div class="field"><label>مدت (روز)</label><input id="cDays" type="number" value="30"></div><div class="field full"><label>پروفایل دسترسی</label><select id="cProfile"><option>Standard</option><option>Premium</option><option>Unlimited</option></select></div></div><button class="primary" style="margin-top:18px;width:100%" onclick="createClient()">CREATE CLIENT PASSPORT</button></div><div class="forge-preview"><div class="eyebrow">LIVE PREVIEW</div><div class="passport"><div class="mark">ALISON / ACCESS PASSPORT</div><h3 id="previewName">NEW CLIENT</h3><p id="previewMeta">STANDARD · 50 GB · 30 DAYS</p><div class="line"></div><small style="color:#58736c">IDENTITY STATUS</small><div style="color:var(--a);font-size:10px;margin-top:5px">● READY TO ISSUE</div><div class="miniqr"></div></div></div></div><div class="panel" style="margin-top:12px"><div class="panelhead"><b>CLIENT REGISTRY</b><span id="clientCount">0</span></div><div class="table"><div class="thead"><span>CLIENT</span><span>PROTOCOL</span><span>TRAFFIC</span><span>STATUS</span><span>ACTIONS</span></div><div id="clientsRows"></div></div></div></section>
<section class="view" id="view-subs"><div class="hero"><div><div class="eyebrow">ACCESS PASSPORT</div><h1>Subscription Core</h1><p>ساب کاملاً مستقل با تجربه‌ی Passport و لینک‌های چندکلاینتی.</p></div><button class="primary" onclick="show('clients')">ساخت پاسپورت</button></div><div class="subhero"><div><div class="eyebrow">PUBLIC ACCESS LAYER</div><h2>Subscription Engine</h2><p>مدیریت لینک‌های اشتراک، گروه‌ها و دسترسی کاربران.</p></div><div class="toggle"><button class="on">LIVE</button><button>SYNC</button></div></div><div class="layout2"><div class="panel"><div class="panelhead"><b>ACTIVE PASSPORTS</b><span>LIVE</span></div><div id="subList" class="feed"></div></div><div class="panel"><div class="panelhead"><b>ACCESS FORMAT</b><span>SUPPORTED</span></div><div class="feed"><div class="feedrow"><i></i><div><b>V2Ray / VLESS</b><small>Native subscription endpoint</small></div></div><div class="feedrow"><i></i><div><b>Clash / Meta</b><small>Compatible access profile</small></div></div><div class="feedrow"><i></i><div><b>Sing-box</b><small>Universal profile</small></div></div></div></div></div></section>
<section class="view" id="view-plans"><div class="sectionbar"><div><h2>Plan Studio</h2><p>پلن‌ها را به شکل محصول قابل فروش مدیریت کن.</p></div></div><div class="plan-grid" id="plansGrid"></div></section>
<section class="view" id="view-analytics"><div class="hero"><div><div class="eyebrow">SIGNAL MONITOR</div><h1>تحلیل شبکه</h1><p>داده‌های telemetry و مصرف را در یک نمای متمرکز ببین.</p></div></div><div class="grid4"><div class="metric"><div class="k">CPU <i class="ti ti-cpu ico"></i></div><strong id="cpu">—</strong><small>SERVER LOAD</small></div><div class="metric"><div class="k">RAM <i class="ti ti-device-desktop-analytics ico"></i></div><strong id="ram">—</strong><small>MEMORY</small></div><div class="metric"><div class="k">UPTIME <i class="ti ti-clock ico"></i></div><strong id="uptime">—</strong><small>SYSTEM</small></div><div class="metric"><div class="k">LATENCY <i class="ti ti-antenna-bars-5 ico"></i></div><strong id="latency">—</strong><small>TCP PROBE</small></div></div><div class="panel" style="margin-top:12px"><div class="panelhead"><b>TELEMETRY</b><span>REFRESHING</span></div><div class="chart" id="chart2"></div></div></section>
<section class="view" id="view-events"><div class="sectionbar"><div><h2>Event Stream</h2><p>رویدادهای مدیریتی و فعالیت‌های سیستم.</p></div></div><div class="panel"><div class="event-stream" id="eventsList" style="padding-top:20px"></div></div></section>
<section class="view" id="view-security"><div class="hero"><div><div class="eyebrow">SECURITY CORE</div><h1>امنیت و دسترسی</h1><p>کنترل نشست‌ها، مدیرها و وضعیت امنیتی.</p></div></div><div class="layout2"><div class="panel"><div class="panelhead"><b>SECURITY CHECK</b><span>LOCAL</span></div><div class="feed"><div class="feedrow"><i></i><div><b>Session protection</b><small>Authenticated dashboard session</small></div><span class="badge">ON</span></div><div class="feedrow"><i></i><div><b>Audit trail</b><small>Activity events available</small></div><span class="badge">ON</span></div><div class="feedrow"><i></i><div><b>Admin isolation</b><small>Permission based access</small></div><span class="badge">ON</span></div></div></div><div class="panel"><div class="panelhead"><b>SESSION</b><span>CONTROL</span></div><div class="feed"><button class="ghost" style="width:100%" onclick="revokeSessions()">لغو نشست‌های دیگر</button></div></div></div></section>
<section class="view" id="view-settings"><div class="hero"><div><div class="eyebrow">SYSTEM CORE</div><h1>پیکربندی</h1><p>ابزارهای پایه سیستم و تنظیمات مدیریتی.</p></div></div><div class="forge"><div class="formpanel"><h3 style="margin-top:0">حساب مدیریت</h3><div class="field"><label>نام کاربری جدید</label><input id="newUser"></div><button class="ghost" style="margin-top:10px" onclick="changeUsername()">ذخیره نام کاربری</button><div class="field" style="margin-top:20px"><label>رمز عبور جدید</label><input id="newPass" type="password"></div><button class="ghost" style="margin-top:10px" onclick="changePassword()">تغییر رمز</button></div><div class="formpanel"><h3 style="margin-top:0">System Diagnostics</h3><div id="diag" style="color:#70838b;font-size:9px;line-height:2.2">برای دریافت وضعیت سیستم، دکمه پایین را بزن.</div><button class="primary" style="margin-top:12px" onclick="openDiagnostics()">RUN DIAGNOSTICS</button></div></div></section>
</div></main></div>
<div class="modal" id="modal"><div class="modalbox"><div class="modalhead"><h3 id="modalTitle">ALISON</h3><button class="close" onclick="closeModal()">×</button></div><div id="modalBody" style="margin-top:15px"></div></div></div><div class="toast" id="toast"></div>
<script>
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let links=[],clients=[],plans=[],events=[];
function sound(kind='click'){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=kind==='success'?740:kind==='error'?180:520;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.025,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.07);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch(e){}}
document.addEventListener('click',e=>{if(e.target.closest('button'))sound()});
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function show(v){sound('success');$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v).classList.add('active');$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const names={overview:'مرکز فرمان',nodes:'آزمایشگاه نود',clients:'Client Forge',subs:'Access Passport',plans:'Plan Studio',analytics:'Signal Monitor',events:'Event Stream',security:'Security Core',settings:'System Core'};$('#crumb').textContent=names[v]||v; if(innerWidth<761)$('#rail').classList.remove('open');if(v==='nodes')loadLinks();if(v==='clients'){loadLinks();loadClients()}if(v==='plans')loadPlans();if(v==='events')loadEvents()}
$$('.nav button[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
function toggleRail(){$('#rail').classList.toggle('open')}
async function api(url,opt={}){const r=await fetch(url,opt);if(r.status===401){location='/login';throw Error('auth')}const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.message||'request failed');return d}
async function refreshAll(){sound('success');await Promise.all([loadLinks(),loadTelemetry(),loadEvents()]);toast('NEXUS synchronized')}
async function loadLinks(){try{const d=await api('/api/links');links=d.links||d.items||[];renderNodes();fillInbound();$('#mNodes').textContent=links.filter(x=>x.active!==false).length}catch(e){}}
function linkName(x){return x.label||x.name||x.remark||x.uuid?.slice(0,8)||'NODE'}
function renderNodes(){const q=($('#nodeSearch')?.value||'').toLowerCase();const arr=links.filter(x=>linkName(x).toLowerCase().includes(q));$('#nodesGrid').innerHTML=arr.length?arr.map((x,i)=>`<article class="node"><div class="node-top"><div class="node-icon"><i class="ti ${['ti-world','ti-sitemap','ti-broadcast','ti-route'][i%4]}"></i></div><span class="status">${x.active===false?'OFFLINE':'ONLINE'}</span></div><h3>${esc(linkName(x))}</h3><div class="proto">${esc(x.protocol||x.network||'VLESS')} · PORT ${esc(x.port||'—')}</div><div class="node-stats"><div><small>USERS</small><b>${x.clients_count??x.client_count??'—'}</b></div><div><small>TRAFFIC</small><b>${fmt(x.used_bytes||x.used_traffic||0)}</b></div><div><small>LIMIT</small><b>${x.limit_bytes?fmt(x.limit_bytes):'∞'}</b></div></div><div class="node-actions"><button onclick="viewNode('${x.uuid}')">OPEN</button><button onclick="nodeClients('${x.uuid}')">CLIENTS</button></div></article>`).join(''):'<div class="empty">هیچ Inboundی پیدا نشد.</div>'}
function fillInbound(){const s=$('#cInbound');if(!s)return;s.innerHTML=links.map(x=>`<option value="${x.uuid}">${esc(linkName(x))}</option>`).join('')}
async function viewNode(id){const d=await api('/api/links/'+id+'/info');openModal(linkName(d),' <pre style="white-space:pre-wrap;color:#789099;font-size:9px">'+esc(JSON.stringify(d,null,2))+'</pre>')}
async function nodeClients(id){const d=await api('/api/links/'+id+'/clients');openModal('CLIENTS · '+linkName(d.inbound||{}),'<div>'+((d.clients||[]).map(x=>`<div class="feedrow"><i></i><div><b>${esc(linkName(x))}</b><small>${esc(x.uuid||'')}</small></div></div>`).join('')||'<div class="empty">No clients</div>')+'</div>')}
function openCreateInbound(){openModal('CREATE INBOUND',`<div class="formgrid"><div class="field"><label>نام</label><input id="miLabel" value="NEXUS-${Date.now().toString().slice(-4)}"></div><div class="field"><label>پورت</label><input id="miPort" type="number" value="443"></div><div class="field"><label>پروتکل</label><select id="miProto"><option>vless</option><option>vmess</option><option>trojan</option><option>shadowsocks</option></select></div><div class="field"><label>Network</label><select id="miNet"><option>ws</option><option>tcp</option><option>grpc</option><option>xhttp</option></select></div></div><button class="primary" style="margin-top:15px;width:100%" onclick="createInbound()">CREATE NODE</button>`)}
async function createInbound(){try{const d=await api('/api/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:$('#miLabel').value,port:Number($('#miPort').value),protocol:$('#miProto').value,network:$('#miNet').value})});toast(d.message||'Inbound created');closeModal();loadLinks()}catch(e){toast(e.message)}}
function preview(){const n=$('#cLabel').value||'NEW CLIENT';$('#previewName').textContent=n.toUpperCase();$('#previewMeta').textContent=($('#cProfile').value||'STANDARD').toUpperCase()+' · '+$('#cLimit').value+' GB · '+$('#cDays').value+' DAYS'}
['cLabel','cLimit','cDays','cProfile'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id)preview()}));
async function createClient(){try{const uid=$('#cInbound').value;if(!uid)return toast('اول یک Inbound بساز');const d=await api('/api/links/'+uid+'/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:$('#cLabel').value||'CLIENT',limit_bytes:Number($('#cLimit').value||0)*1024*1024*1024,expires_days:Number($('#cDays').value||0)})});toast('Client Passport issued');sound('success');await loadClients();}catch(e){toast(e.message)}}
async function loadClients(){clients=[];for(const x of links.slice(0,30)){try{const d=await api('/api/links/'+x.uuid+'/clients');clients.push(...(d.clients||[]).map(c=>({...c,_inbound:linkName(x)})))}catch(e){}}renderClients()}
function renderClients(){const q=($('#clientSearch')?.value||'').toLowerCase();const arr=clients.filter(x=>(linkName(x)+' '+(x._inbound||'')).toLowerCase().includes(q));$('#clientCount').textContent=arr.length;$('#clientsRows').innerHTML=arr.map(x=>`<div class="tr"><span><b>${esc(linkName(x))}</b><small style="display:block;color:#53666f;font-size:7px">${esc(x._inbound||'')}</small></span><span>${esc(x.protocol||'VLESS')}</span><span>${fmt(x.used_bytes||x.used_traffic||0)} / ${x.limit_bytes?fmt(x.limit_bytes):'∞'}</span><span><span class="badge">${x.active===false?'OFFLINE':'ACTIVE'}</span></span><span class="rowactions"><button onclick="openClient('${x.uuid}')"><i class="ti ti-eye"></i></button></span></div>`).join('')||'<div class="empty">No clients</div>'}
async function openClient(id){const x=clients.find(c=>c.uuid===id)||{};openModal('CLIENT PASSPORT',`<div class="passport"><div class="mark">ALISON / ACCESS PASSPORT</div><h3>${esc(linkName(x))}</h3><p>${esc(x.protocol||'VLESS')} · ${esc(x.uuid||'')}</p><div class="line"></div><small style="color:#58736c">SUBSCRIPTION</small><div style="word-break:break-all;color:#9fb6b1;font-size:9px;margin-top:6px">${location.origin}/subscription/${encodeURIComponent(x.uuid||'')}</div><button class="primary" style="margin-top:14px" onclick="copyText('${location.origin}/subscription/${encodeURIComponent(x.uuid||'')}')">COPY PASSPORT LINK</button></div>`)}
async function loadPlans(){try{const d=await api('/api/plans');plans=d.plans||d||[];$('#plansGrid').innerHTML=plans.map((p,i)=>`<article class="plan ${i===1?'featured':''}"><div class="eyebrow">PLAN ${String(i+1).padStart(2,'0')}</div><h3>${esc(p.name||'PLAN')}</h3><div class="price">${esc(String(p.stars??p.price??0))} <small style="font-size:9px;color:#6b7f87">STARS</small></div><ul><li>Traffic · ${p.data_limit?fmt(p.data_limit):'∞'}</li><li>Duration · ${p.duration_days||p.days||'—'} days</li><li>Status · ${p.active===false?'OFF':'ACTIVE'}</li></ul></article>`).join('')||'<div class="empty">No plans</div>'}catch(e){$('#plansGrid').innerHTML='<div class="empty">Plan API unavailable</div>'}}
async function loadTelemetry(){try{const d=await api('/api/telemetry');$('#cpu').textContent=d.cpu_percent!=null?Math.round(d.cpu_percent)+'%':'—';$('#ram').textContent=d.memory_percent!=null?Math.round(d.memory_percent)+'%':'—';$('#uptime').textContent=d.uptime_human||d.uptime||'—';$('#latency').textContent=d.latency_ms!=null?d.latency_ms+'ms':'—';const bars=$('#chart2');bars.innerHTML=Array.from({length:28},(_,i)=>`<span class="bar" style="height:${20+Math.random()*70}%"></span>`).join('');}catch(e){}}
async function loadEvents(){try{const d=await api('/api/activity');events=d.items||d.activities||d||[];const arr=Array.isArray(events)?events.slice(0,12):[];$('#eventsList').innerHTML=arr.map(x=>`<div class="event"><b>${esc(x.action||x.event||x.message||'Activity')}</b><small>${esc(x.username||x.actor||'system')} · ${esc(x.created_at||x.timestamp||'')}</small></div>`).join('')||'<div class="empty">No recent events</div>';$('#feed').innerHTML=arr.slice(0,6).map(x=>`<div class="feedrow"><i></i><div><b>${esc(x.action||x.event||'Activity')}</b><small>${esc(x.username||x.actor||'system')}</small></div><time>LIVE</time></div>`).join('')||'<div class="empty">No activity</div>'}catch(e){}}
function renderChart(){const c=$('#chart');c.innerHTML=Array.from({length:30},()=>`<span class="bar" style="height:${12+Math.random()*85}%"></span>`).join('')}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('show')};function closeModal(){$('#modal').classList.remove('show')}
async function openDiagnostics(){try{const d=await api('/api/system/diagnostics');openModal('SYSTEM DIAGNOSTICS','<pre style="white-space:pre-wrap;color:#789099;font-size:9px">'+esc(JSON.stringify(d,null,2))+'</pre>')}catch(e){toast(e.message)}}
async function revokeSessions(){try{await api('/api/security/revoke-other-sessions',{method:'POST'});toast('Other sessions revoked')}catch(e){toast(e.message)}}
async function changeUsername(){const v=$('#newUser').value.trim();if(!v)return;try{await api('/api/change-username',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:v})});toast('Username changed')}catch(e){toast(e.message)}}
async function changePassword(){const v=$('#newPass').value;if(!v)return;try{await api('/api/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:v})});toast('Password changed')}catch(e){toast(e.message)}}
async function logout(){await fetch('/logout');location='/login'}
async function copyText(t){await navigator.clipboard?.writeText(t);toast('Copied to clipboard');sound('success')}
function fmt(n){n=Number(n||0);if(n<1024)return n+' B';const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return n.toFixed(n>10?0:1)+' '+u[i]}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
renderChart();loadLinks();loadTelemetry();loadEvents();preview();setInterval(()=>{loadTelemetry();loadLinks()},15000);
</script></body></html>'''
